---
extends: airbnb-base
env:
  node: true
  es6: true
parser: typescript-eslint-parser
parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true
rules:
  semi:
    - error
    - always
  no-unused-vars: off
  no-undef: off
  import/no-unresolved: off
  import/extensions: off
  sort-imports: error
  import/no-duplicates: off
  brace-style:
    - error
    - stroustrup
  no-console: off
  no-plusplus: off
  sort-imports: off